
version: '3.1'

services:
  client: 
    container_name: clinefile
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
    -  /app/node_modules
    - ./client:/app
    ports:
    - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - server

  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
    - .:/code
    ports:
      - 5000:5000
    command: npm start
    links:
     - mongo
  
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    volumes:
      - ./datamongo:/data/mongo
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    links: 
    - mongo
